-- script do banco de dados utilizado na aplicação

CREATE TABLE public.pessoa (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	nome varchar(255) NULL,
	idDepartamento int8,
	CONSTRAINT pessoa_pkey PRIMARY KEY (id)
);

CREATE TABLE public.tarefa (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	titulo varchar(255) NULL,
	descricao varchar(255) NULL,
	prazo date NULL,
	idDepartamento int8 NULL,
	duracao int4 NOT NULL,
	idPessoa int8 NULL,
	finalizada bool NOT NULL,
	CONSTRAINT tarefa_pkey PRIMARY KEY (id)
);


create table departamento (
id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
titulo varchar(30)

);

--Registro de Departamento;

insert into departamento (titulo) values ('Financeiro');
insert into departamento (titulo) values ('Comercial');
insert into departamento (titulo) values ('Desenvolvimento');

select * from departamento d ;

-- Registro de Pessoas; 

insert into pessoa (nome, idDepartamento) values ('Camila', 1);
insert into pessoa (nome, idDepartamento) values ('Pedro', 2);
insert into pessoa (nome, idDepartamento) values ('Fabiano', 3);
insert into pessoa (nome, idDepartamento) values ('Raquel', 3);
insert into pessoa (nome, idDepartamento) values ('Paatricia', 3);
insert into pessoa (nome, idDepartamento) values ('Joaquim', 1);

select * from pessoa p; 

--Registro de tarefa

insert into tarefa (titulo, descricao, prazo, iddepartamento, duracao, idpessoa, finalizada) 
  values ('Validar NF Janeiro', 'Validar notas recebidas no mês de janeiro', '2022-02-15', 1, 14, 1, true);
insert into tarefa (titulo, descricao, prazo, iddepartamento, duracao, idpessoa, finalizada) 
  values ('Bug 352', 'Corrigir bug 352 na versão 1.25', '2022-05-10', 3, 25, null, false);
insert into tarefa (titulo, descricao, prazo, iddepartamento, duracao, idpessoa, finalizada) 
  values ('liberação da versão 1.24', 'Disponibilizar pacote para testes', '2022-02-02', 3, 2, 3, false);
insert into tarefa (titulo, descricao, prazo, iddepartamento, duracao, idpessoa, finalizada) 
  values ('Reuniao A', 'Reunião do cliente A para apresentação do produto', '2022-02-05', 2, 5, null, false);
insert into tarefa (titulo, descricao, prazo, iddepartamento, duracao, idpessoa, finalizada) 
  values ('Reuniao final', 'Fechamento contrato', '2022-03-28', 2, 6, null, false);
insert into tarefa (titulo, descricao, prazo, iddepartamento, duracao, idpessoa, finalizada) 
  values ('Pagamento 01/2022', 'Realizar pagamento dos fornecedores', '2022-01-31', 1, 6, 1, true);
insert into tarefa (titulo, descricao, prazo, iddepartamento, duracao, idpessoa, finalizada) 
 values ('Bug 401', 'Corrigir bug 401 na versão 1.20', '2022-02-01', 3, 2, 4, true);
insert into tarefa (titulo, descricao, prazo, iddepartamento, duracao, idpessoa, finalizada) 
 values ('Bug 399', 'Corrigir bug 399 na versão 1.20', '2022-01-28', 3, 6, 5, true);
insert into tarefa (titulo, descricao, prazo, iddepartamento, duracao, idpessoa, finalizada) 
  values ('Reuniao B', 'Reunião do cliente B para apresentação do produto', '2022-01-31', 2, 5, 2, true);
insert into tarefa (titulo, descricao, prazo, iddepartamento, duracao, idpessoa, finalizada) 
  values ('Validar NF Fevereiro', 'Validar notas recebidas no mês de Fevereiro', '2022-03-15', 1, 14, 6, false);

select * from tarefa;

-- 1- Montar select que retorne nome do departamento, quantidade de tarefas finalizadas 
-- e quantidade de tarefas não finalizadas e adicione o  resultado do select

select d.titulo , t.finalizada , count(*) from tarefa t
left join departamento d 
on d.id = t.iddepartamento 
group by d.titulo, t.finalizada
order by 1;


--2 Montar select que retorne a pessoa que mais gastou horas em janeiro de 2022 e adicione o resultado do select

select  p.nome , sum(t.duracao) as totalHoras from tarefa t 
left join pessoa p 
on t.idpessoa = p.id 
where p.nome is not null
group by p.nome
order by 2 desc limit 1;


-- Montar select que retorne título da tarefa, prazo, se tiver pessoa alocada na tarefa
-- exibir como “Encaminhado para + nome do pessoa” caso contrário “Pendente” e 
-- total de horas que essa pessoa já gastou. Ordenar por prazo decrescente. E adicione o resultado do select

select t.titulo , t.prazo , t.duracao ,
case 
	when t.idpessoa  is not null then concat('Encaminhado para ', p.nome )  
	else 'Pendente'
end as Pessoa_Alocada
from tarefa t 
left join pessoa p 
on t.idpessoa  = p.id 
order by 2 desc;
