quarkus:
  message: default message
  flyway:
    baseline-on-migrate: true


'%Teste':
  quarkus:
    message: 'teste configuration'
    datasource:
      username: evee
      password: senha123
      jdbc:
        url: jdbc:postgresql://0.0.0.0:5432/teste
    hibernate-orm:
      database:
        generation: drop-and-create
        log:
          sql: true


'%Int':
  quarkus:
    message: 'int configuration'
    datasource:
      username: evee
      password: senha123
      jdbc:
        url: jdbc:postgresql://0.0.0.0:5432/integracao
    hibernate-orm:
      database:
        generation: update
      log:
        sql: true